/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/ads/ad-view.component';
import * as i2 from '../../../app/shared/analytics.service';
import * as i3 from '@angular/http';
const styles_AdViewComponent:any[] = ([] as any[]);
export const RenderType_AdViewComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AdViewComponent,data:{}});
export function View_AdViewComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'a',[['target',
      '_blank']],[[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:i1.AdViewComponent = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.onClick()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n   '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),0,'img',[['class','image'],['height','150'],
          ['width','150']],[[8,'src',4]],(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n   '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),1,'div',[['class','title']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n     ',
      '\n   '])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),
      ['\n']))],(null as any),(_ck,_v) => {
    var _co:i1.AdViewComponent = _v.component;
    const currVal_0:any = _co.ad.url;
    _ck(_v,0,0,currVal_0);
    const currVal_1:any = i0.ɵinlineInterpolate(1,'',_co.ad.image_url,'');
    _ck(_v,2,0,currVal_1);
    const currVal_2:any = _co.ad.title;
    _ck(_v,5,0,currVal_2);
  });
}
export function View_AdViewComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'sponsored-event',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdViewComponent_0,
      RenderType_AdViewComponent)),i0.ɵprd(512,(null as any),i2.AnalyticsService,i2.AnalyticsService,
      [i3.Http]),i0.ɵdid(49152,(null as any),0,i1.AdViewComponent,[i2.AnalyticsService],
      (null as any),(null as any))],(null as any),(null as any));
}
export const AdViewComponentNgFactory:i0.ComponentFactory<i1.AdViewComponent> = i0.ɵccf('sponsored-event',
    i1.AdViewComponent,View_AdViewComponent_Host_0,{ad:'ad'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9hZHMvYWQtdmlldy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ydWRvbGZvL0NvZGUvQW5ndWxhci1jb3Vyc2UvYXBwL2Fkcy9hZC12aWV3LmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9hZHMvYWQtdmlldy50ZW1wbGF0ZS5odG1sIiwibmc6Ly8vaG9tZS9ydWRvbGZvL0NvZGUvQW5ndWxhci1jb3Vyc2UvYXBwL2Fkcy9hZC12aWV3LmNvbXBvbmVudC50cy5BZFZpZXdDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YSAoY2xpY2spPVwib25DbGljaygpXCJcbiAgIFtocmVmXT1cImFkLnVybFwiXG4gICB0YXJnZXQ9XCJfYmxhbmtcIj5cbiAgIDxpbWcgd2lkdGg9XCIxNTBcIiBoZWlnaHQ9XCIxNTBcIlxuICAgICAgICBjbGFzcz1cImltYWdlXCJcbiAgICAgICAgc3JjPVwie3thZC5pbWFnZV91cmx9fVwiIC8+XG4gICA8ZGl2IGNsYXNzPVwidGl0bGVcIj5cbiAgICAge3thZC50aXRsZX19XG4gICA8L2Rpdj5cbjwvYT5cbiIsIjxzcG9uc29yZWQtZXZlbnQ+PC9zcG9uc29yZWQtZXZlbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO0lBQUE7SUFBQTtJQUFHO01BQUE7TUFBQTtJQUFBO0lBQUg7RUFBQSxnQ0FFbUIsMENBQ2hCO2FBQUE7VUFBQTtVQUFBLGdCQUU4QiwwQ0FDOUI7TUFBQTtNQUFBLDRDQUFtQjtNQUFBLFdBRWIsdUNBQ0w7TUFBQTs7SUFSRDtJQURILFdBQ0csU0FESDtJQUtRO0lBRkwsV0FFSyxTQUZMO0lBR21CO0lBQUE7Ozs7b0JDTnRCO01BQUE7Z0NBQUE7TUFBQSxrQkFBQTtNQUFBOzs7In0=
