/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.datatable[_ngcontent-%COMP%] {\n    width: 50%;\n}'];
//# sourceMappingURL=report.style.less.shim.ngstyle.js.map