/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['body[_ngcontent-%COMP%] {\n    padding: 0 1%;\n    margin: 0;\n    font-family: "Helvetica Neue", "Calibri Light", Roboto, sans-serif;\n    font-size: 16px;\n}\n\n.datatable[_ngcontent-%COMP%] {\n    height: 70vh;\n\n    &.material {\n        .datatable-header {\n            background-color: #4e9a06;\n\n            .datatable-header-cell {\n                color: #ffffff;\n\n                &.sort-active {\n                    background-color: #73d216;\n                }\n            }\n        }\n    }\n}\n\na[_ngcontent-%COMP%] {\n    color: black;\n    text-decoration: none;\n\n    &:visited {\n        color: black;\n    }\n}\n\n.headline[_ngcontent-%COMP%] {\n    font-size: 2em;\n    color: #00aa4f;\n    text-align: center;\n}\n\nnav[_ngcontent-%COMP%] {\n    text-align: center;\n\n    a {\n        border-left: 1px solid #b2cb7a;\n        color: black;\n        padding: 0.5em;\n        font-size: 1.2em;\n\n        &:first-of-type {\n            border-left: none;\n        }\n\n        &:hover {\n            text-decoration: underline;\n        }\n    }\n\n    .active {\n        font-weight: bold;\n    }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9hcHAuc3R5bGUubGVzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3J1ZG9sZm8vQ29kZS9Bbmd1bGFyLWNvdXJzZS9hcHAvYXBwLnN0eWxlLmxlc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
