/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/examples/example-animation.component';
const styles_ExampleAnimationComponent:any[] = ([] as any[]);
export const RenderType_ExampleAnimationComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ExampleAnimationComponent,data:{'animation':[{type:7,name:'helloWorld',
        definitions:[{type:0,name:'initial',styles:{type:6,styles:{backgroundColor:'#aaaaaa'},
            offset:(null as any)}},{type:0,name:'final',styles:{type:6,styles:{backgroundColor:'#ffffff'},
            offset:(null as any)}},{type:1,expr:'initial <=> final',animation:[{type:4,
            styles:(null as any),timings:500}],options:(null as any)}],options:{}}]}});
export function View_ExampleAnimationComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      [[24,'@helloWorld',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  Hello Angular Animations!\n'])),(_l()(),
          i0.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    var _co:i1.ExampleAnimationComponent = _v.component;
    const currVal_0:any = _co.animationState;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_ExampleAnimationComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'example-animation',
      ([] as any[]),(null as any),(null as any),(null as any),View_ExampleAnimationComponent_0,
      RenderType_ExampleAnimationComponent)),i0.ɵdid(49152,(null as any),0,i1.ExampleAnimationComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ExampleAnimationComponentNgFactory:i0.ComponentFactory<i1.ExampleAnimationComponent> = i0.ɵccf('example-animation',
    i1.ExampleAnimationComponent,View_ExampleAnimationComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9leGFtcGxlcy9leGFtcGxlLWFuaW1hdGlvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ydWRvbGZvL0NvZGUvQW5ndWxhci1jb3Vyc2UvYXBwL2V4YW1wbGVzL2V4YW1wbGUtYW5pbWF0aW9uLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9leGFtcGxlcy9leGFtcGxlLWFuaW1hdGlvbi50ZW1wbGF0ZS5odG1sIiwibmc6Ly8vaG9tZS9ydWRvbGZvL0NvZGUvQW5ndWxhci1jb3Vyc2UvYXBwL2V4YW1wbGVzL2V4YW1wbGUtYW5pbWF0aW9uLmNvbXBvbmVudC50cy5FeGFtcGxlQW5pbWF0aW9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHAgW0BoZWxsb1dvcmxkXT1cImFuaW1hdGlvblN0YXRlXCI+XG4gIEhlbGxvIEFuZ3VsYXIgQW5pbWF0aW9ucyFcbjwvcD5cbiIsIjxleGFtcGxlLWFuaW1hdGlvbj48L2V4YW1wbGUtYW5pbWF0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQWtDLG9FQUU5QjtpQkFBQTs7SUFGRDtJQUFILFdBQUcsU0FBSDs7OztvQkNBQTtNQUFBOzBDQUFBLFVBQUE7TUFBQTs7OyJ9
