/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './example-animation.component.ngfactory';
import * as i2 from '../../../app/examples/example-animation.component';
import * as i3 from './example-form.component.ngfactory';
import * as i4 from '../../../app/examples/example-form.component';
import * as i5 from '@angular/forms';
import * as i6 from '../../../app/examples/example.component';
const styles_ExampleComponent:any[] = ([] as any[]);
export const RenderType_ExampleComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ExampleComponent,data:{}});
export function View_ExampleComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Examples'])),(_l()(),i0.ɵted((null as any),['\n\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['Angular Animations'])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'example-animation',([] as any[]),
              (null as any),(null as any),(null as any),i1.View_ExampleAnimationComponent_0,
              i1.RenderType_ExampleAnimationComponent)),i0.ɵdid(49152,(null as any),
          0,i2.ExampleAnimationComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Angular Forms'])),(_l()(),
          i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'example-form',([] as any[]),(null as any),(null as any),(null as any),
          i3.View_ExampleFormComponent_0,i3.RenderType_ExampleFormComponent)),i0.ɵdid(49152,
          (null as any),0,i4.ExampleFormComponent,[i5.FormBuilder],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_ExampleComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ExampleComponent_0,
      RenderType_ExampleComponent)),i0.ɵdid(49152,(null as any),0,i6.ExampleComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ExampleComponentNgFactory:i0.ComponentFactory<i6.ExampleComponent> = i0.ɵccf('ng-component',
    i6.ExampleComponent,View_ExampleComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9leGFtcGxlcy9leGFtcGxlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3J1ZG9sZm8vQ29kZS9Bbmd1bGFyLWNvdXJzZS9hcHAvZXhhbXBsZXMvZXhhbXBsZS5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3J1ZG9sZm8vQ29kZS9Bbmd1bGFyLWNvdXJzZS9hcHAvZXhhbXBsZXMvZXhhbXBsZS50ZW1wbGF0ZS5odG1sIiwibmc6Ly8vaG9tZS9ydWRvbGZvL0NvZGUvQW5ndWxhci1jb3Vyc2UvYXBwL2V4YW1wbGVzL2V4YW1wbGUuY29tcG9uZW50LnRzLkV4YW1wbGVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+RXhhbXBsZXM8L2gxPlxuXG48aDI+QW5ndWxhciBBbmltYXRpb25zPC9oMj5cbjxleGFtcGxlLWFuaW1hdGlvbj48L2V4YW1wbGUtYW5pbWF0aW9uPlxuXG48aDI+QW5ndWxhciBGb3JtczwvaDI+XG48ZXhhbXBsZS1mb3JtPjwvZXhhbXBsZS1mb3JtPlxuIiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQSw4QkFBYTtNQUVqQjtVQUFBLDBEQUFJO1VBQUEseUJBQXVCLHVDQUMzQjtpQkFBQTtjQUFBO3FEQUFBLFVBQUE7VUFBQTtNQUF1Qyx5Q0FFdkM7VUFBQTtVQUFBLGdCQUFJLGtEQUFrQjtpQkFBQSx3QkFDdEI7VUFBQTsyRUFBQSxVQUFBO1VBQUE7TUFBNkI7OztvQkNON0I7TUFBQTtpQ0FBQSxVQUFBO01BQUE7OzsifQ==
