/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.event-image[_ngcontent-%COMP%] {\n    border: 1px solid #c8e7ea;\n}\n\n.event-title[_ngcontent-%COMP%] {\n    color: #00aa4f;\n    font-weight: bold;\n    font-family: serif;\n    font-size: 1.1em;\n}\n\n.event-more-info[_ngcontent-%COMP%] {\n    color: #333333;\n    padding: 1em;\n    animation: fadein 2s;\n}\n\n.event-description[_ngcontent-%COMP%] {\n    font-size: 0.9em;\n}\n\n@keyframes fadein {\n    from { opacity: 0; }\n    to { opacity: 1; }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9ldmVudHMvZXZlbnQtdmlldy5zdHlsZS5sZXNzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcnVkb2xmby9Db2RlL0FuZ3VsYXItY291cnNlL2FwcC9ldmVudHMvZXZlbnQtdmlldy5zdHlsZS5sZXNzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
